### ISSUE TITLE
[BUG] `freeze_support()` error when trying to start comfyui process

### ISSUE THREAD

**Issue by ckcfcc** [ModelSurge/sd-webui-comfyui#100]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/dark/ai_projects/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui_pre_main.py", line 5, in <module>
    from lib_comfyui import (
  File "/Users/dark/ai_projects/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/argv_conversion.py", line 2, in <module>
    from lib_comfyui import webui_settings
  File "/Users/dark/ai_projects/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/webui_settings.py", line 3, in <module>
    from lib_comfyui import ipc
  File "/Users/dark/ai_projects/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc.py", line 38, in <module>
    'webui': parallel_utils.CallbackWatcher(parallel_utils.CallbackQueue(call_fully_qualified)),
  File "/Users/dark/ai_projects/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/parallel_utils.py", line 45, in __init__
    manager = ctx.Manager()
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/managers.py", line 562, in start
    self._process.start()
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/dark/dev_lib/miniconda3/envs/sd/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by ljleb** [comment]
This is due to particularities in how the multiprocessing module works. When we switch to subprocess to start the comfyui process, this shouldn't be a problem anymore.

**Comment by ljleb** [comment]
related: #99

**Comment by achiever1984** [comment]
Same problem. How can I fix it?

**Comment by ljleb** [comment]
To fix this issue, you can:
- switch operating systems
- open a PR to fix the code
- wait for plads or myself to push a fix, for which I do not have an ETA

**Comment by ljleb** [comment]
This should be fixed now. You can now pick in the settings which communication mechanism between comfyui and the webui to use based on your preference. If you run into issues with "Shared memory", I suggest switching to "File system".
