### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess

### ISSUE THREAD

**Issue by SetasSan** [ModelSurge/sd-webui-comfyui#15]
I installed: [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
added this extension.

OS: Linux mint 21
python: 3.10.6
torch: 1.13.1+cu117

ComfyUI forks on its own.
SD webui works on its own.

but using ComfyUI inside SD webui  after pressing "Queue prompt" gives me this error:
```
Exception in thread Thread-4 (prompt_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/media/entity/HDD/AI/ComfyUI/main.py", line 43, in prompt_worker
    e.execute(item[-2], item[-1])
  File "/media/entity/HDD/AI/ComfyUI/execution.py", line 200, in execute
    torch.cuda.ipc_collect()
  File "/media/entity/HDD/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 578, in ipc_collect
    _lazy_init()
  File "/media/entity/HDD/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

**Comment by John-WL** [comment]
I tried using the 'spawn' method for torch.multiprocessing like the error mesage suggested. It's in the pr that I linked to this issue. Let me know if it works or not.

**Comment by ljleb** [comment]
Merged as spawn was the intended method. Will try to test on linux on my side to make sure we haven't missed anything else.

Note that this extension is still very early in developement, expect some instability in the short term.

**Comment by SetasSan** [comment]
Issue is fixed. good job ;)
