### ISSUE TITLE
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8189): address already in use

### ISSUE THREAD

**Issue by schoenid** [ModelSurge/sd-webui-comfyui#166]
After installing the module I've got an Error:

```
[sd-webui-comfyui] Started callback listeners for process webui
[sd-webui-comfyui] Starting subprocess for comfyui...
[ComfyUI] [sd-webui-comfyui] Setting up IPC...
[ComfyUI] [sd-webui-comfyui] Using inter-process communication strategy: File system
[ComfyUI] [sd-webui-comfyui] Started callback listeners for process comfyui
[ComfyUI] [sd-webui-comfyui] Patching ComfyUI...
Startup time: 7.6s (scripts unloaded callback: 0.6s, load scripts: 2.2s, create ui: 0.9s, gradio launch: 2.1s, app_started_callback: 1.7s).
[ComfyUI] Total VRAM 7971 MB, total RAM 64037 MB
[ComfyUI] xformers version: 0.0.22.post4
[ComfyUI] Set vram state to: NORMAL_VRAM
[ComfyUI] Device: cuda:0 NVIDIA GeForce RTX 3060 : native
[ComfyUI] VAE dtype: torch.bfloat16
[ComfyUI] Using xformers cross attention
[ComfyUI] [sd-webui-comfyui] Launching ComfyUI with arguments: --listen 127.0.0.1 --port 8189
[ComfyUI] 
Import times for custom nodes:
[ComfyUI]    0.0 seconds: /home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_io.py
[ComfyUI]    0.0 seconds: /home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_save_image.py
[ComfyUI]    0.0 seconds: /home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_proxy_nodes.py
[ComfyUI]
Traceback (most recent call last):
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 94, in <module>
    main()
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 42, in main
    start_comfyui()
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 89, in start_comfyui
    runpy.run_path(os.path.join(os.getcwd(), 'main.py'), {'comfyui_print': comfyui_print}, '__main__')
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/main.py", line 201, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/main.py", line 105, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "<string>", line 546, in start
  File "/home/sd/Tech/Linux/stable-diffusion-webui/venv/lib/python3.10/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8189): address already in use
[ComfyUI] [sd-webui-comfyui] Stopped callback listeners for process comfyui
[ComfyUI] registered ws - postprocess_img2img - f51e279b18ef4acfa8b2077243da8836
[ComfyUI] registered ws - postprocess_txt2img - 1b8170c00bff490ab621bb785e088d9c
[ComfyUI] registered ws - postprocess_latent_img2img - 95a770393123459d8ede2af063febdbc
[ComfyUI] registered ws - postprocess_latent_txt2img - e6c61c846fdc4767b45045fdb3e825a9
[ComfyUI] registered ws - sandbox_tab - f118f3f00dd845ffa6fbe2f83ef97edf
[ComfyUI] registered ws - preprocess_img2img - 885407e652de4579ad44e1042a3d34a8
[ComfyUI] registered ws - preprocess_latent_img2img - 33e3bee734494444ae6c8fd145e12765
[ComfyUI] registered ws - postprocess_txt2img - 1b8170c00bff490ab621bb785e088d9c
[ComfyUI] registered ws - sandbox_tab - f118f3f00dd845ffa6fbe2f83ef97edf
[ComfyUI] registered ws - postprocess_img2img - f51e279b18ef4acfa8b2077243da8836
[ComfyUI] registered ws - postprocess_latent_txt2img - e6c61c846fdc4767b45045fdb3e825a9
[ComfyUI] registered ws - postprocess_latent_img2img - 95a770393123459d8ede2af063febdbc
[ComfyUI] registered ws - preprocess_img2img - 885407e652de4579ad44e1042a3d34a8
[ComfyUI] registered ws - preprocess_latent_img2img - 33e3bee734494444ae6c8fd145e12765
```

So in the txt2img tab the ComfyUI workflow will also be displayed different:
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/15383666/069a2791-48de-4225-b476-2f4bd7b65856)

than in the ComfyUI tab:
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/15383666/0ef7c7a8-8122-4770-8847-54843c01b525)

Is this intended and are these separated workflow models?

System information:
WebUI: version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.12  •  torch: 2.1.0+cu121  •  xformers: 0.0.22.post4  •  gradio: 3.41.2  •  checkpoint: [77ff71a2ec](https://google.com/search?q=77ff71a2ecd94a3cb7d9456bd7f4950971a43cceb49b4ba066e8523a1e6634e7)

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.2.0-1014-lowlatency (64-bit)
Graphics Platform: X11
Processors: 16 × 13th Gen Intel® Core™ i7-13700K
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2

**Comment by John-WL** [comment]
Yes, the workflow that appears under the txt2img and img2img tabs are itentionally different. This is because these workflows work hand-in-hand with the respective diffusion pipelines of each tabs. 

The default workflow takes the images, and does nothing with it (sends it right back to the output). 

You can do additional process on the generated image using the "From Webui" node as image input, and then sending it back to the webui viewport with the "To Webui" node. 

I hope this makes things clear. Make sure to check the wiki of this github repo if you're still not sure. 

As for the address in use, there could be a couple reasons. Do you have another comfyui running at that address, by any chance? Comfyui seems to still be working in the webui in your case despite the address being already in use.

**Comment by schoenid** [comment]
Well, Thank you!

Something strange:

After 3rd or 4th newstart it's working now.

The console prompts:
```
[sd-webui-comfyui] Started callback listeners for process webui
[sd-webui-comfyui] Starting subprocess for comfyui...
Applying attention optimization: xformers... done.
Startup time: 53.7s (prepare environment: 37.2s, import torch: 2.6s, import gradio: 0.7s, setup paths: 0.8s, other imports: 0.4s, load scripts: 5.8s, initialize extra networks: 0.1s, create ui: 1.8s, gradio launch: 3.1s, app_started_callback: 1.0s).
Model loaded in 6.4s (load weights from disk: 0.5s, create model: 0.5s, apply weights to model: 4.9s, calculate empty prompt: 0.4s).
[ComfyUI] [sd-webui-comfyui] Setting up IPC...
[ComfyUI] [sd-webui-comfyui] Using inter-process communication strategy: File system
[ComfyUI] [sd-webui-comfyui] Started callback listeners for process comfyui
[ComfyUI] [sd-webui-comfyui] Patching ComfyUI...
[ComfyUI] Total VRAM 7971 MB, total RAM 64037 MB
[ComfyUI] xformers version: 0.0.22.post4
[ComfyUI] Set vram state to: NORMAL_VRAM
[ComfyUI] Device: cuda:0 NVIDIA GeForce RTX 3060 : native
[ComfyUI] VAE dtype: torch.bfloat16
[ComfyUI] Using xformers cross attention
[ComfyUI] [sd-webui-comfyui] Launching ComfyUI with arguments: --listen 127.0.0.1 --port 8189
[ComfyUI] 
Import times for custom nodes:
[ComfyUI]    0.0 seconds: /home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_save_image.py
[ComfyUI]    0.0 seconds: /home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_io.py
[ComfyUI]    0.0 seconds: /home/sd/Tech/Linux/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_proxy_nodes.py
[ComfyUI]
[ComfyUI] Starting server

[ComfyUI] To see the GUI go to: http://127.0.0.1:8189
[ComfyUI] registered ws - sandbox_tab - 44d52fc0b0d44b24a253886d9eb09260
[ComfyUI] registered ws - postprocess_latent_txt2img - e27fcbda1a6545fab0d2415a44f57a5e
[ComfyUI] registered ws - preprocess_img2img - 4bc27ae07a8e4fd4915ecfbc26e8686a
[ComfyUI] registered ws - postprocess_img2img - 93d093b5040942e7b6d71588b22b2bf1
[ComfyUI] registered ws - postprocess_latent_img2img - d9b9577ad4734a778af35cded1994ca7
[ComfyUI] registered ws - postprocess_txt2img - c7f473c7f01a46a999e24d7fb2f0bd3d
[ComfyUI] registered ws - preprocess_latent_img2img - ffb00ba132e140bc944225bdf385ac0c
```

The interesting part is:
```
Applying attention optimization: xformers... done.
Startup time: 53.7s (prepare environment: 37.2s, import torch: 2.6s, import gradio: 0.7s, setup paths: 0.8s, other imports: 0.4s, load scripts: 5.8s, initialize extra networks: 0.1s, create ui: 1.8s, gradio launch: 3.1s, app_started_callback: 1.0s).
Model loaded in 6.4s (load weights from disk: 0.5s, create model: 0.5s, apply weights to model: 4.9s, calculate empty prompt: 0.4s).
```
which was not there before. 

:)

**Comment by John-WL** [comment]
Weird indeed! I'm glad it's working now.
