### ISSUE TITLE
process remains running after exiting automatic1111

### ISSUE THREAD

**Issue by throwromans** [ModelSurge/sd-webui-comfyui#181]
the python process launched for comfyui  is not properly terminated and remains running after exiting automatic1111 which causes issues and errors if trying to relaunch automatic1111 while the original process is still running

**Comment by John-WL** [comment]
Interresting, what is your OS?

**Comment by throwromans** [comment]
> Interesting, what is your OS?

Windows 10 Home
Version	22H2
OS build	19045.3693
Experience	Windows Feature Experience Pack 1000.19053.1000.0

Python 3.11.4

**Comment by throwromans** [comment]
traceback 
`Traceback (most recent call last):
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 94, in <module>
    main()
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 41, in main
    patch_comfyui()
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 80, in patch_comfyui
    paths.share_webui_folder_paths()
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\webui\paths.py", line 10, in share_webui_folder_paths
    webui_folder_paths = get_webui_folder_paths()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 20, in wrapper
    res = current_callback_proxies[process_id].get(args=(function.__module__, function.__qualname__, args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\callback.py", line 70, in get
    self._args_sender.send((args if args is not None else (), kwargs if kwargs is not None else {}))
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\payload.py", line 45, in send
    self._strategy.set_data(lock_file, pickle.dumps(value))
  File "C:\Users\throwromans\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\strategies.py", line 98, in set_data
Model loaded in 6.6s (load weights from disk: 1.7s, create model: 0.5s, apply weights to model: 3.6s, calculate empty prompt: 0.7s).
    self._shm = SharedMemory(name=self._shm_name, create=True, size=data_len)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\shared_memory.py", line 143, in __init__
    raise FileExistsError(
FileExistsError: [WinError 183] File exists: 'ipc_payload_args_webui'
[ComfyUI] [sd-webui-comfyui] Stopped callback listeners for process comfyui`

**Comment by ljleb** [comment]
One workaround we could try is preventing from running the webui code that replaces the sigint handler with a direct python exit.

I think this could work because it should let the atexit callbacks run.

I don't like this solution because if another extension does the same thing, there could be a difference in what the sigint handler actually does in each extension. I'll ask what the webui maintainers think and see if there could be instead a solution on their side.

**Comment by ljleb** [comment]
This went over my head a little bit. A possible fix is to have the comfyui server continually ping the webui for status and then let it kill itself when it gets no reply. This is all happening from a local machine so no reliability method should be needed.
