### ISSUE TITLE
extension started spewing out in console

### ISSUE THREAD

**Issue by f-rank** [ModelSurge/sd-webui-comfyui#185]
"*** Error running postprocess_batch_list: D:\WORK\conda_envs\automatic\stable-diffusion-webui\extensions\sd-webui-comfyui\scripts\comfyui.py
    lib_comfyui.ipc.callback.RemoteError: '1d60c3da-0985-4724-95dd-80ddd2f87fa4'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "D:\WORK\conda_envs\automatic\stable-diffusion-webui\modules\scripts.py", line 667, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\WORK\conda_envs\automatic\stable-diffusion-webui\extensions\sd-webui-comfyui\scripts\comfyui.py", line 57, in postprocess_batch_list
        iframe_requests.extend_infotext_with_comfyui_workflows(p, self.get_tab())
      File "D:\WORK\conda_envs\automatic\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\iframe_requests.py", line 121, in extend_infotext_with_comfyui_workflows
        ComfyuiIFrameRequests.validate_amount_of_nodes_or_throw(
      File "D:\WORK\conda_envs\automatic\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "D:\WORK\conda_envs\automatic\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\iframe_requests.py", line 78, in validate_amount_of_nodes_or_throw
        workflow_graph = get_workflow_graph(workflow_type_id)
      File "D:\WORK\conda_envs\automatic\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\iframe_requests.py", line 145, in get_workflow_graph
        return ComfyuiIFrameRequests.send(request='webui_serialize_graph', workflow_type=workflow_type_id)
      File "D:\WORK\conda_envs\automatic\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 20, in wrapper
        res = current_callback_proxies[process_id].get(args=(function.__module__, function.__qualname__, args, kwargs))
      File "D:\WORK\conda_envs\automatic\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\callback.py", line 73, in get
        raise res.error from res
    KeyError: '1d60c3da-0985-4724-95dd-80ddd2f87fa4'

---"

and trying to add the from webui and to webui doesn't work either, the nodes appear empty. This is on latest everything really.
Trying to drag an image with a comfy post-process in it results in an error.
Something changed, probably in comfy that's my guess.

**Comment by John-WL** [comment]
I believe this is the combination of 1 update we made to manage multiple Webui UIs at the same time, and a ComfyUI update. 

The error in itself comes from the workflow types not being registered to the extension. It is supposed to not appear if the workflow types are registeted properly. 

As for the error that you get when dropping an image, this is probably a ComfyUI update yes.

**Comment by f-rank** [comment]
@John-WL thanks for the elucidating explanation about the unregistered types, and the update "mismatch" situation.

Just to further clear what I stated, the drag image was in reference to an image rendered with auto1111, containing info about comfyui extension parameters.

Also, at start it also always loads the same default workflow for some reason.
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/1836566/f1444a7b-0fcc-427a-b1d9-23d340cc3f4c)

Just putting it here so anyone experiencing similar problems can compare, or even elaborate.

**Comment by John-WL** [comment]
Is there a reason why the comfy side-panel isn't hidden in the IFrame? 
I just updated everything and it doesn't show up for me (it is intended to be hidden to improve visibility). 

Also, it's definitely weird that the default workflows are not loading for each workflow type on startup. 
I was not able to reproduce this so far. 

As for loading workflows from A1111 generated images, see #112.

**Comment by f-rank** [comment]
The side-panel started popping up there like that.
I update and now I am getting:

1) that seems related to specific nodes:
"[ComfyUI] Traceback (most recent call last):
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes\nodes.py", line 15, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'"

2) also related to specific nodes:
"[ComfyUI] Traceback (most recent call last):
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ImageProcessing\__init__.py", line 1, in <module>
    from .imageprocessing import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ImageProcessing\imageprocessing.py", line 2, in <module>
    from kornia.filters import bilateral_blur, unsharp_mask
ImportError: cannot import name 'bilateral_blur' from 'kornia.filters' (D:\WORK\conda_envs\automatic\stable-diffusion-webui\venv\lib\site-packages\kornia\filters\__init__.py)"

3) Related to a third different pack of nodes
"[ComfyUI] Traceback (most recent call last):
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\Agents\Assistant.py", line 9, in <module>
    import autogen
ModuleNotFoundError: No module named 'autogen'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\__init__.py", line 127, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
  File "C:\Users\Utilizador\.conda\envs\automatic\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\Agents\Assistant.py", line 21, in <module>
    import autogen
ModuleNotFoundError: No module named 'autogen'

[ComfyUI] Cannot import D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT module for custom nodes: No module named 'autogen'"


So there are three packs that fail, though they work under bare Comfyui.
Then there's no to/from webui and that workflow loads up with the sidebar menu, same thing in full window.

**Comment by ljleb** [comment]
I think this problem is caused by the extension not finding the venv your comfyui needs to work normally and falling back on the webui venv. Could you please share with us:

1. the path the extension uses to find comfyui (the path in the webui settings page)
2. the effective path to comfyui home (the directory that contains directories `comfy`, `comfy_extras`, `custom_nodes`, etc.)
3. does the comfyui home folder above at 2. contain a `venv` folder?
4. if it doesn't, which python environment do you usually use? it appears to be a conda env from what I gather

if you are using a conda env, we will have to add support for that. the extension currently only supports pip venvs with the `venv` directory directly inside the comfyui home folder.

**Comment by f-rank** [comment]
1. Comfyui install location is set to D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI
2. D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI
3. It doesn't
4. As this is the windows portable comfyui I gather it must be using D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\python_embeded. I never saw a directory called venv anywhere inside comfyui.

Not using a conda env for comfyui, using a conda env for webui though. They just happen to both be downstream from a directory called conda_envs.

This all worked up to about a month ago. Some node groups didn't load because they were clearly looking for stuff that doesn't exist in webui conda env. Now it just loads that workflow and shows the menu bar, while showing void to and from Webui nodes when added.

> I think this problem is caused by the extension not finding the venv your comfyui needs to work normally and falling back on the webui venv. Could you please share with us:
> 
>     1. the path the extension uses to find comfyui (the path in the webui settings page)
> 
>     2. the effective path to comfyui home (the directory that contains directories `comfy`, `comfy_extras`, `custom_nodes`, etc.)
> 
>     3. does the comfyui home folder above at 2. contain a `venv` folder?
> 
>     4. if it doesn't, which python environment do you usually use? it appears to be a conda env from what I gather
> 
> 
> if you are using a conda env, we will have to add support for that. the extension currently only supports pip venvs with the `venv` directory directly inside the comfyui home folder.

**Comment by ljleb** [comment]
The extension now checks for the portable python path location. Let us know if you still run into issues using the extension.

**Comment by f-rank** [comment]
Updated and made sure dependencies are met in the portable python env.
Still the same thing in auto webui though. Thanks for trying.
I better reinstall auto from scratch see if it fixes it.
Thank you for looking into it.

> The extension now checks for the portable python path location. After updating and making sure the dependencies of your custom nodes have been met in the portable python environment, let us know if you still run into issues using the extension.

**Comment by f-rank** [comment]
Here is a full log from the time I start auto webui up to where I try to generate an image, based on the info I used by dragging previous generation metadata. That used the comfyui extension to apply some post-processing on an image. This is with everything updated, including your fix, that solves all the problems with the installed custom nodes dependencies.
An image is produced but 

Comfyui window looks like this throughout it
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/1836566/f4933a68-d463-4f39-a7e6-ea7c5d3bc4f7)

I'll hold out on the re-install case something comes up. I tried to remove the extension and install it back but that didn't change anything.


> Alright, I'll let you reinstall from scratch. Before doing that, could you please share the entire logs? I wonder if we could be missing a critical piece of information. i.e. the entire logs from the webui starting to finishing starting with the error after one attempted generation.

**Comment by ljleb** [comment]
Just to be sure, clicking on the "Reload ComfyUI interfaces (client side)" doesn't fix the problem, correct?

**Comment by ljleb** [comment]
I just pushed a small update to the reload button that may give us more information, make sure to run this on the latest version of the extension.

**Comment by f-rank** [comment]
https://pastebin.com/7uSEvBgq
this is the full console output from webui launch to pressing the Reload button, on latest update.

> I just pushed a small update to the reload button that may give us more information, make sure to test this on the latest version of the extension.

**Comment by ljleb** [comment]
Yes, but what about the browser console?

**Comment by f-rank** [comment]
https://pastebin.com/ghtMnLX6
The full browser console output after pressing the reload button

> Yes, but what about the browser console? Are there errors in the browser (not the server, but i.e. chrome or firefox) after clicking on the reload button?

**Comment by ljleb** [comment]
Thanks. I see that the browser can't find any of the js files of the extension, which is why the iframes fail to load. Now we have to figure out why the server returns 404 on them.

**Comment by f-rank** [comment]
@ljleb all I got under the debugger that identifies the iframe is this:
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/1836566/786a5db8-6a83-47b0-96a4-5610ed1f941b)

there are other entries connecting to same port on 127.0.0.1 but they don't highlight the element.
Something more specific I can provide ?

**Comment by ljleb** [comment]
> Something more specific I can provide?

For now I can't think of another piece of information that could help here. I tried to look into it a little bit with everything you shared, but to no avail so far. I think I'll need a bit more time to find a way to reproduce. I did find one or two improvements to the repo to commit but nothing that can fix this really.

I'm sorry, I unfortunately have to focus on real life for the next week at least, but I should be able to check back here after. If anyone finds a solution and wants this fixed sooner, PRs are welcome.

**Comment by ljleb** [comment]
Maybe one last thing to try could be to toggle on/off the reverse proxy and restart fully the webui between each settings update. The reverse proxy intercepts js files and replaces some of the import paths to make it work, so maybe it is related. I'm not confident this will do anything but it's worth a try I think.

**Comment by f-rank** [comment]
Tried the options with a full restart between updates. Nothing changes though. It's always loading the side menu and the workflow. At least the node dependencies got fixed.
Thanks for looking into it.

> Maybe one last thing to try could be to toggle on/off the reverse proxy and restart fully the webui between each settings update. The reverse proxy intercepts js files and replaces some of the import paths to make comfyui js extensions work, so maybe it is related to the 404s. I'm not confident this will do anything but it's worth a try I think.

**Comment by f-rank** [comment]
Something changed after this last update.
Now one of the webui's node is populated.
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/1836566/784a4b7a-71ee-4837-8d5d-cefee5274950)

**Comment by ljleb** [comment]
That's... interesting. Does it work if you temporarily disable every comfyui nodes? A quick way to do this is to use a completely new comfyui install location and then download comfyui using the extension or by manually cloning to that location.

**Comment by f-rank** [comment]
Somehow too much stuff in the updates made me miss your reply. Sorry.
I think you're correct about what would fix it, makes sense, will have to eat the bullet after finishing some stuff I am doing atm.
Clean Install here I go. Thanks @ljleb 

> That's... interesting. Does it work if you temporarily disable every comfyui nodes? A quick way to do this is to use a completely new comfyui install location and then download comfyui using the extension or by manually cloning to that location.
> 
> Maybe another thing to try at this point would be a factory install of the webui + sd-webui-comfyui + comfyui in another directory to see if the problem still occurs there.

**Comment by trpipher** [comment]
I am still having this issue
When installing comfyui for the first time after the installation i get this: https://pastebin.com/hFBLVsRM
Then i get this when genning
---

    KeyError: '2c6790ce-6b3c-42f1-84f5-3d851710a489'
        raise res.error from res
      File "/storage/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/callback.py", line 73, in get
        res = current_callback_proxies[process_id].get(args=(function.__module__, function.__qualname__, args, kwargs))
      File "/storage/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 20, in wrapper
        return ComfyuiIFrameRequests.send(request='webui_serialize_graph', workflow_type=workflow_type_id)
      File "/storage/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/iframe_requests.py", line 145, in get_workflow_graph
        workflow_graph = get_workflow_graph(workflow_type_id)
      File "/storage/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/iframe_requests.py", line 78, in validate_amount_of_nodes_or_throw
        return function(*args, **kwargs)
      File "/storage/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
        ComfyuiIFrameRequests.validate_amount_of_nodes_or_throw(
      File "/storage/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/iframe_requests.py", line 121, in extend_infotext_with_comfyui_workflows
        iframe_requests.extend_infotext_with_comfyui_workflows(p, self.get_tab())
      File "/storage/stable-diffusion-webui/extensions/sd-webui-comfyui/scripts/comfyui.py", line 57, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "/storage/stable-diffusion-webui/modules/scripts.py", line 766, in postprocess_batch_list
    Traceback (most recent call last):

    The above exception was the direct cause of the following exception:

    lib_comfyui.ipc.callback.RemoteError: '2c6790ce-6b3c-42f1-84f5-3d851710a489'


Also get this in UI for webui nodes
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/6992101/24cfb4fe-1c74-44a2-825d-8631c813958c)


Note: im using paperspace and connecting via nginx to the paperspace

**Comment by PladsElsker** [comment]
Did the PR we merged today fix part of the issue?

**Comment by PladsElsker** [comment]
For the webui key error, restarting the UI (ctrl + F5) should do the job. Is that not working? 

You can't expect the UI to function properly if the key error is there, you NEED the Webui key to be registered by the extension when generating an image.
