### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by breiti35** [ModelSurge/sd-webui-comfyui#195]
ERROR:root:!!! Exception during processing !!!
ERROR:root:lib_comfyui.ipc.callback.RemoteError: 'Module' object has no attribute 'transformer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\comfyui_custom_nodes\webui_proxy_nodes.py", line 23, in load_checkpoint
    proxies.ClipWrapper(proxies.Clip()),
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\webui\proxies.py", line 144, in __init__
    self.patcher = ModelPatcher(self.cond_stage_model)
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\webui\proxies.py", line 14, in __init__
    self.load_device = model.device
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\webui\proxies.py", line 235, in __getattr__
    res = Clip.sd_clip_getattr(item)
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 20, in wrapper
    res = current_callback_proxies[process_id].get(args=(function.__module__, function.__qualname__, args, kwargs))
  File "G:\auto\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\callback.py", line 73, in get
    raise res.error from res
AttributeError: 'Module' object has no attribute 'transformer'

![Screenshot 2023-12-28 182605](https://github.com/ModelSurge/sd-webui-comfyui/assets/77593678/4455b7d7-ed0f-4fe9-9171-1840acd85bf2)

**Comment by ljleb** [comment]
Currently the webui checkpoint node is very unstable and not actively maintained. Plads and I are prioritizing issues that break the extension completely. If other people complain about this node I will consider looking into fixing the code.

A basic thing that needs to be done is opening an issue in comfyui to request for a more stable programming interface that supports our use case. I will do this later today.

**Comment by azamet90** [comment]
> Currently the webui checkpoint node is very unstable and not actively maintained. Plads and I are prioritizing issues that break the extension completely. If other people complain about this node I will consider looking into fixing the code.
> 
> A basic thing that needs to be done is opening an issue in comfyui to request for a more stable programming interface that supports our use case. I will do this later today.

i dont know if this is the same bug but also have this one:

```
*** Error running postprocess_batch_list: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/scripts/comfyui.py[00:01<00:00,  9.61it/s]
    lib_comfyui.ipc.callback.RemoteError: '72e933d2-9228-4960-8f46-bfcd1fa89238'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/xxx/Masaüstü/stable-diffusion-webui/modules/scripts.py", line 766, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/scripts/comfyui.py", line 57, in postprocess_batch_list
        iframe_requests.extend_infotext_with_comfyui_workflows(p, self.get_tab())
      File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/iframe_requests.py", line 121, in extend_infotext_with_comfyui_workflows
        ComfyuiIFrameRequests.validate_amount_of_nodes_or_throw(
      File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/iframe_requests.py", line 78, in validate_amount_of_nodes_or_throw
        workflow_graph = get_workflow_graph(workflow_type_id)
      File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/iframe_requests.py", line 145, in get_workflow_graph
        return ComfyuiIFrameRequests.send(request='webui_serialize_graph', workflow_type=workflow_type_id)
      File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 20, in wrapper
        res = current_callback_proxies[process_id].get(args=(function.__module__, function.__qualname__, args, kwargs))
      File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/callback.py", line 73, in get
        raise res.error from res
    KeyError: '72e933d2-9228-4960-8f46-bfcd1fa89238'
```

**Comment by ljleb** [comment]
No, this is a different bug. This is a known issue where the webui client id needs to be made slightly more robust: #192
