### ISSUE TITLE
can't update neither patch

### ISSUE THREAD

**Issue by StudioXV** [ModelSurge/sd-webui-comfyui#199]
Hi there, since las updat I get this error... any help? thankyou!

Traceback (most recent call last):
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\custom_extension_injector.py", line 87, in patch_prompt_server_add_routes
    add_routes_ast_function.body[2].value.args[0].elts[0:0] = [extra_line_of_code.body[0].value]
AttributeError: 'For' object has no attribute 'value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 98, in <module>
    main()
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 43, in main
    patch_comfyui()
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 85, in patch_comfyui
    custom_extension_injector.register_webui_extensions()
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\custom_extension_injector.py", line 14, in register_webui_extensions
    register_custom_scripts(script_paths)
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\custom_extension_injector.py", line 33, in register_custom_scripts
    patch_prompt_server_add_routes(parsed_class, custom_scripts_path_list)
  File "C:\GitHub\SuperSD\extensions\sd-webui-comfyui\lib_comfyui\custom_extension_injector.py", line 89, in patch_prompt_server_add_routes
    raise RuntimeError("Cannot patch comfyui as it is not up to date")
RuntimeError: Cannot patch comfyui as it is not up to date

**Comment by jayododds** [comment]
After uninstalling and reinstalling the plugin in an attempt to get it to see torch (see my previous issue) I get this same error. I have tried setting the ICS to file system as suggested elsewhere - but that didn't seem to make a difference either.

**Comment by WhiteKnight666** [comment]
Same issue... I met the issue too today...And I am sure it is up to date... I don't know why....

**Comment by WhiteKnight666** [comment]
Spent 4H in this issue but I cannot find a solution....exhaust...

**Comment by jayododds** [comment]
As much as I don't want to - I may have to setup a standalone and link it - I was hoping to keep it all in the same automatic folder family, but oh well. 🙃

**Comment by John-WL** [comment]
Just to cIarify, @jayododds I don't think this is the same issue as you had in #198.

**Comment by John-WL** [comment]
Okay, should be fixed. They added a for loop in the middle of the function, so we were patching the wrong thing. I also updated the error message so that people don't spend 4h trying to fix a non-fixable issue.

**Comment by StudioXV** [comment]
right now it works for me. The only thing was the comfyui manager were not there. I'm reinstalling sd-webui-conmfyui. it might be there if I'm not wrong.. if not I'll try to do it manually (I'm noob). I'll let you know about the reinstalling. Good job!

**Comment by StudioXV** [comment]
right now it works for me. The only thing was the comfyui manager were not there. I'm reinstalling sd-webui-conmfyui. it might be there if I'm not wrong.. if not I'll try to do it manully (I'm noob)

**Comment by StudioXV** [comment]
Everything ok!

**Comment by jayododds** [comment]
The update got it running but now I'm onto the white screen in tab issue :) Getting closer!

**Comment by WhiteKnight666** [comment]
I updated the new version, but a new issue come up....
[ComfyUI] To see the GUI go to: http://127.0.0.1:8189
Exception in thread Thread-8 (<lambda>):
Traceback (most recent call last):
  File "E:\Stable diffusion\sd-webui-aki-v4.5\python\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "E:\Stable diffusion\sd-webui-aki-v4.5\python\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "E:\Stable diffusion\sd-webui-aki-v4.5\python\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "asyncio\base_events.py", line 863, in getaddrinfo
  File "concurrent\futures\thread.py", line 58, in run
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\Stable diffusion\sd-webui-aki-v4.5\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2240, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\Stable diffusion\sd-webui-aki-v4.5\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2238, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "E:\Stable diffusion\sd-webui-aki-v4.5\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2226, in get_cache
    json_obj = await get_data(uri)
  File "E:\Stable diffusion\sd-webui-aki-v4.5\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 516, in get_data
    async with session.get(uri) as resp:
  File "E:\Stable diffusion\sd-webui-aki-v4.5\python\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "E:\Stable diffusion\sd-webui-aki-v4.5\python\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "E:\Stable diffusion\sd-webui-aki-v4.5\python\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "E:\Stable diffusion\sd-webui-aki-v4.5\python\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "E:\Stable diffusion\sd-webui-aki-v4.5\python\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]

**Comment by John-WL** [comment]
@WhiteKnight666 Are you using 2 different venvs for your Webui and ComfyUI installation? I could be wrong but I feel like some ComfyUI code leads to an error in the venv of your A1111 install.
