### ISSUE TITLE
KeyError: '0de71eda-d31a-42f5-b865-2e19ccc1cf66'

### ISSUE THREAD

**Issue by ljleb** [ModelSurge/sd-webui-comfyui#224]
### Discussed in https://github.com/ModelSurge/sd-webui-comfyui/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **JFZeroZHUO** July 15, 2024</sup>
**_I NEED HELP~~_**

*** Error running postprocess_batch_list: D:\AIGC\stable-diffusion-webui\extensions\sd-webui-comfyui\scripts\comfyui.py
    lib_comfyui.ipc.callback.RemoteError: '0de71eda-d31a-42f5-b865-2e19ccc1cf66'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "D:\AIGC\stable-diffusion-webui\modules\scripts.py", line 766, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\AIGC\stable-diffusion-webui\extensions\sd-webui-comfyui\scripts\comfyui.py", line 57, in postprocess_batch_list
        iframe_requests.extend_infotext_with_comfyui_workflows(p, self.get_tab())
      File "D:\AIGC\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\iframe_requests.py", line 121, in extend_infotext_with_comfyui_workflows
        ComfyuiIFrameRequests.validate_amount_of_nodes_or_throw(
      File "D:\AIGC\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "D:\AIGC\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\iframe_requests.py", line 78, in validate_amount_of_nodes_or_throw
        workflow_graph = get_workflow_graph(workflow_type_id)
      File "D:\AIGC\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\iframe_requests.py", line 145, in get_workflow_graph
        return ComfyuiIFrameRequests.send(request='webui_serialize_graph', workflow_type=workflow_type_id)
      File "D:\AIGC\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 20, in wrapper
        res = current_callback_proxies[process_id].get(args=(function.__module__, function.__qualname__, args, kwargs))
      File "D:\AIGC\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\callback.py", line 73, in get
        raise res.error from res
    KeyError: '0de71eda-d31a-42f5-b865-2e19ccc1cf66'</div>

**Comment by ljleb** [comment]
@JFZeroZHUO what steps should be taken to reproduce the issue?
