### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package

### ISSUE THREAD

**Issue by carlosInverse** [ModelSurge/sd-webui-comfyui#228]
when i install comfyui by stable diffusion v1.10.1, i don't know where i'm so wrong, can you help me?

venv "E:\AI Drawing\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Installing sd-webui-comfyui requirement: changing portalocker version from 2.10.1 to 2.7.0
Launching Web UI with arguments: --xformers --enable-insecure-extension-access
[-] ADetailer initialized. version: 24.9.0, num models: 22
ControlNet preprocessor location: E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-09-12 04:29:24,732 - ControlNet - INFO - ControlNet v1.1.455
Loading weights [31829c378d] from E:\AI Drawing\stable-diffusion-webui\models\Stable-diffusion\3dAnimationDiffusion_v10.safetensors
2024-09-12 04:29:25,335 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: E:\AI Drawing\stable-diffusion-webui\configs\v1-inference.yaml
E:\AI Drawing\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: "resume_download" is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use "force_download=True".
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set “share=True” in “launch()".
[sd-webui-comfyui] Started callback listeners for process webui
[sd-webui-comfyui] Starting subprocess for comfyui...
IIB Database file has been successfully backed up to the backup folder.
Startup time: 13.1s (prepare environment: 3.8s, import torch: 3.0s, import gradio: 0.8s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 0.5s, list SD models: 0.1s, load scripts: 2.7s, create ui: 0.7s, gradio launch: 0.4s).
Applying attention optimization: xformers... done.
[ComfyUI] [sd-webui-comfyui] Setting up IPC...
[ComfyUI] [sd-webui-comfyui] Using inter-process communication strategy: Shared memory
[ComfyUI] [sd-webui-comfyui] Started callback listeners for process comfyui
[ComfyUI] [sd-webui-comfyui] Patching ComfyUI...
Model loaded in 4.7s (load weights from disk: 0.7s, create model: 0.4s, apply weights to model: 1.0s, load textual inversion embeddings: 2.3s, calculate empty prompt: 0.1s).
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[ComfyUI] [sd-webui-comfyui] Launching ComfyUI with arguments: --listen 127.0.0.1 --port 8189
[ComfyUI] [START] Security scan
[ComfyUI] [DONE] Security scan
[ComfyUI] ## ComfyUI-Manager: installing dependencies done.
[ComfyUI] ** ComfyUI startup time: 2024-09-12 04:29:32.394336
[ComfyUI] ** Platform: Windows
[ComfyUI] ** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
[ComfyUI] ** Python executable: E:\AI Drawing\stable-diffusion-webui\venv\Scripts\python.exe
[ComfyUI] ** ComfyUI Path: E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI
[ComfyUI] ** Log path: E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfyui.log
Traceback (most recent call last):
  File "E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 98, in <module>
    main()
  File "E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 44, in main
    start_comfyui()
  File "E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 93, in start_comfyui
    runpy.run_path(os.path.join(os.getcwd(), 'main.py'), {'comfyui_print': comfyui_print}, '__main__')
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\AI Drawing\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\main.py", line 66, in <module>
    import utils.extra_config
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package

**Comment by curl3y** [comment]
I think i found a workaround,
remove line 66 in main.py and add
```
import sys
sys.path.append("C:/path to/ComfyUI/utils/")
import extra_config
```

**Comment by carlosInverse** [comment]
I think it's package name confilict, so i rename utils to utilsed and edit line 66 in main.py, utils.extra_config to utilsed.extra_config.
then we need install torchaudio=2.1.2 by self, at the end, it's work.

**Comment by sozturk88** [comment]
# Thank you it has solved my issue.

> I think i found a workaround, remove line 66 in main.py and add
> 
> ```
> import sys
> sys.path.append("C:/path to/ComfyUI/utils/")
> import extra_config
> ```

**Comment by pwlivewire** [comment]
> I think it's package name confilict, so i rename utils to utilsed and edit line 66 in main.py, utils.extra_config to utilsed.extra_config. then we need install torchaudio=2.1.2 by self, at the end, it's work.

This worked for me, it had been driving me mad so thank you so much for posting this here.

**Comment by ChrisTello** [comment]
> I think it's package name confilict, so i rename utils to utilsed and edit line 66 in main.py, utils.extra_config to utilsed.extra_config. then we need install torchaudio=2.1.2 by self, at the end, it's work.

where and how do i install torchaudio?

**Comment by carlosInverse** [comment]
> > I think it's package name confilict, so i rename utils to utilsed and edit line 66 in main.py, utils.extra_config to utilsed.extra_config. then we need install torchaudio=2.1.2 by self, at the end, it's work.
> 
> where and how do i install torchaudio?

In your patch \stable-diffusion-webui\venv\ ，open cmd and  start up venv, then you can use pip command to install torchaudio=2.1.2

**Comment by ChrisTello** [comment]
> > > I think it's package name confilict, so i rename utils to utilsed and edit line 66 in main.py, utils.extra_config to utilsed.extra_config. then we need install torchaudio=2.1.2 by self, at the end, it's work.
> > 
> > 
> > where and how do i install torchaudio?
> 
> In your patch \stable-diffusion-webui\venv\ ，open cmd and start up venv, then you can use pip command to install torchaudio=2.1.2

i tried but i get this error

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 2.1.2 which is incompatible.

i should say, comfyui will open but if i try to load workflows it freezes. even simple ones or trying to load the default freeze it.

**Comment by Salminar** [comment]
>> I think i found a workaround, remove line 66 in main.py and add
> 
> ```
> import sys
> sys.path.append("C:/path to/ComfyUI/utils/")
> import extra_config
> ```

What main.py are you editing? There are a ton in the directories of stable diffusion.

**Comment by curl3y** [comment]
> > > I think i found a workaround, remove line 66 in main.py and add
> > 
> > 
> > ```
> > import sys
> > sys.path.append("C:/path to/ComfyUI/utils/")
> > import extra_config
> > ```
> 
> What main.py are you editing? There are a ton in the directories of stable diffusion.

The main.py located in the the directory "drive:\etc\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\main.py"

**Comment by Salminar** [comment]
Hu ...

My line 57 to 67 are :
`

> module_name = os.path.splitext(script_path)[0]
>         try:
>             spec = importlib.util.spec_from_file_location(module_name, script_path)
>             module = importlib.util.module_from_spec(spec)
>             spec.loader.exec_module(module)
>             return True
>         except Exception as e:
>             logging.error(f"Failed to execute startup-script: {script_path} / {e}")
>         return False

`


So  i should put the import in the exception?

**Comment by curl3y** [comment]
> Hu ...
> 
> My line 57 to 67 are : `
> 
> > module_name = os.path.splitext(script_path)[0]
> > try:
> > spec = importlib.util.spec_from_file_location(module_name, script_path)
> > module = importlib.util.module_from_spec(spec)
> > spec.loader.exec_module(module)
> > return True
> > except Exception as e:
> > logging.error(f"Failed to execute startup-script: {script_path} / {e}")
> > return False
> 
> `
> 
> So i should put the import in the exception?

The fix I suggested was over six months ago and the scripts have changed significantly since then,
The line 66 that was removed from main.py was "import utils.extra_config" and then I inserted the extra lines of code. 

I have slept a few times since then so i dont fully remember why the error happened or even why my fix fixed it, it was more luck than skill.

The only thing I can suggest is removing line 11 in the current script which is the same import command and then try adding the extra lines, absolutely no idea if this will work, I dont even have a working example to try this out, as the install I fixed my end has been deleted a while ago.

**Comment by roiniti** [comment]
> I think i found a workaround, remove line 66 in main.py and add
> 
> ```
> import sys
> sys.path.append("C:/path to/ComfyUI/utils/")
> import extra_config
> ```

For me this works using it in main line 11 as you said but also you will need to do the same in line 11 of app/custom_node_manager.py to import json_recursive:
```
import sys
sys.path.append("C:/path to/ComfyUI/utils/")
from json_util import merge_json_recursive
````

**Comment by cliffwillard** [comment]
this issue happens because this path `{install_dir}\webui\extensions\sd-webui-comfyui\ComfyUI\comfy` added to sys path. This folder contains `utils.py` file which overrides imported `utils` module. This happens in `webui\extensions\sd-webui-comfyui\lib_comfyui\custom_extension_injector.py:21`
```
@ipc.restrict_to_process('comfyui')
def register_custom_scripts(custom_scripts_path_list):
    from nodes import EXTENSION_WEB_DIRS
```
I was able to resolve the issue by adding the line which removes the path causing the issue right after the import:
```
@ipc.restrict_to_process('comfyui')
def register_custom_scripts(custom_scripts_path_list):
    from nodes import EXTENSION_WEB_DIRS
    import sys;sys.path.remove(os.path.join(os.getcwd(), 'comfy'))
```
