### ISSUE TITLE
unable to get working

### ISSUE THREAD

**Issue by lgwjames** [ModelSurge/sd-webui-comfyui#229]
installed on my sd forge via the install by url.
gone to the setting and put in the folder as per guide

console error

```
[ComfyUI] [sd-webui-comfyui] Launching ComfyUI with arguments: --listen 127.0.0.1 --port 8189
[ComfyUI] [START] Security scan
[ComfyUI] [DONE] Security scan
[ComfyUI] ## ComfyUI-Manager: installing dependencies done.
[ComfyUI] ** ComfyUI startup time: 2024-09-16 08:06:33.337326
[ComfyUI] ** Platform: Windows
[ComfyUI] ** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
[ComfyUI] ** Python executable: C:\Users\jessi\Desktop\SD Forge\webui\venv\Scripts\python.exe
[ComfyUI] ** ComfyUI Path: C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\ComfyUI
[ComfyUI] ** Log path: C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\ComfyUI\comfyui.log
Traceback (most recent call last):
  File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 98, in <module>
    main()
  File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 44, in main
    start_comfyui()
  File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 93, in start_comfyui
    runpy.run_path(os.path.join(os.getcwd(), 'main.py'), {'comfyui_print': comfyui_print}, '__main__')
  File "C:\Users\jessi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\jessi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\jessi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\ComfyUI\main.py", line 66, in <module>
    import utils.extra_config
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package
*** Error executing callback after_component_callback for C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py
    Traceback (most recent call last):
      File "C:\Users\jessi\Desktop\SD Forge\webui\modules\script_callbacks.py", line 365, in after_component_callback
        c.callback(component, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py", line 30, in on_after_component
        patches.watch_prompts(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\patches.py", line 34, in watch_prompts
        getattr(component, event_listener)(
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\gradio\events.py", line 490, in event_trigger
        raise AttributeError(
    AttributeError: Cannot call change outside of a gradio.Blocks context.

---
*** Error executing callback after_component_callback for C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py
    Traceback (most recent call last):
      File "C:\Users\jessi\Desktop\SD Forge\webui\modules\script_callbacks.py", line 365, in after_component_callback
        c.callback(component, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py", line 30, in on_after_component
        patches.watch_prompts(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\patches.py", line 34, in watch_prompts
        getattr(component, event_listener)(
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\gradio\events.py", line 490, in event_trigger
        raise AttributeError(
    AttributeError: Cannot call change outside of a gradio.Blocks context.

---
*** Error executing callback after_component_callback for C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py
    Traceback (most recent call last):
      File "C:\Users\jessi\Desktop\SD Forge\webui\modules\script_callbacks.py", line 365, in after_component_callback
        c.callback(component, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py", line 30, in on_after_component
        patches.watch_prompts(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\patches.py", line 34, in watch_prompts
        getattr(component, event_listener)(
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\gradio\events.py", line 490, in event_trigger
        raise AttributeError(
    AttributeError: Cannot call change outside of a gradio.Blocks context.

---
*** Error executing callback after_component_callback for C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py
    Traceback (most recent call last):
      File "C:\Users\jessi\Desktop\SD Forge\webui\modules\script_callbacks.py", line 365, in after_component_callback
        c.callback(component, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py", line 30, in on_after_component
        patches.watch_prompts(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\patches.py", line 34, in watch_prompts
        getattr(component, event_listener)(
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\gradio\events.py", line 490, in event_trigger
        raise AttributeError(
    AttributeError: Cannot call change outside of a gradio.Blocks context.

---
*** Error executing callback after_component_callback for C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py
    Traceback (most recent call last):
      File "C:\Users\jessi\Desktop\SD Forge\webui\modules\script_callbacks.py", line 365, in after_component_callback
        c.callback(component, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py", line 30, in on_after_component
        patches.watch_prompts(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\patches.py", line 34, in watch_prompts
        getattr(component, event_listener)(
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\gradio\events.py", line 490, in event_trigger
        raise AttributeError(
    AttributeError: Cannot call change outside of a gradio.Blocks context.

---
*** Error executing callback after_component_callback for C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py
    Traceback (most recent call last):
      File "C:\Users\jessi\Desktop\SD Forge\webui\modules\script_callbacks.py", line 365, in after_component_callback
        c.callback(component, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\callbacks.py", line 30, in on_after_component
        patches.watch_prompts(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\sd-webui-comfyui\lib_comfyui\webui\patches.py", line 34, in watch_prompts
        getattr(component, event_listener)(
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\gradio\events.py", line 490, in event_trigger
        raise AttributeError(
    AttributeError: Cannot call change outside of a gradio.Blocks context.
```

i have comfyui installed on its own and tested and works.

**Comment by DenisBalan** [comment]
same issue here! on debian

**Comment by DenisBalan** [comment]
Nov 08 10:28:27 ollama-ct bash[14137]: 2024-11-08 10:28:27,409 - ControlNet - INFO - ControlNet UI callback registered.
Nov 08 10:28:28 ollama-ct bash[14137]: /root/stable-diffusion-webui-forge/modules/ui_settings.py:57: GradioDeprecationWarning: unexpected argument for Button: label
Nov 08 10:28:28 ollama-ct bash[14137]:   res = comp(label=info.label, value=fun(), elem_id=elem_id, **(args or {}))
Nov 08 10:28:28 ollama-ct bash[14137]: Model selected: {'checkpoint_info': {'filename': '/root/stable-diffusion-webui-forge/models/Stable-diffusion/flux1-dev-bnb-nf4-v2.safetensors', 'hash': 'f0770152'}, 'additional_modules': [], 'unet_storage_dtype': None}
Nov 08 10:28:28 ollama-ct bash[14137]: Using online LoRAs in FP16: False
Nov 08 10:28:29 ollama-ct bash[14137]: Running on local URL:  http://0.0.0.0:7860
Nov 08 10:28:30 ollama-ct bash[14137]: To create a public link, set `share=True` in `launch()`.
Nov 08 10:28:32 ollama-ct bash[14137]: [sd-webui-comfyui] Could not find ComfyUI under directory "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/ComfyUI". The server will NOT be started.
Nov 08 10:28:32 ollama-ct bash[14137]: [sd-webui-comfyui] Created a reverse proxy route to ComfyUI: /sd-webui-comfyui/comfyui
Nov 08 10:28:32 ollama-ct bash[14137]: Startup time: 15.1s (load scripts: 0.8s, initialize google blockly: 8.0s, create ui: 2.5s, gradio launch: 1.5s, add APIs: 2.2s).
Nov 08 10:28:33 ollama-ct bash[14137]: *** Error executing callback after_component_callback for /root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/callbacks.py
Nov 08 10:28:33 ollama-ct bash[14137]:     Traceback (most recent call last):
Nov 08 10:28:33 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/modules/script_callbacks.py", line 365, in after_component_callback
Nov 08 10:28:33 ollama-ct bash[14137]:         c.callback(component, **kwargs)
Nov 08 10:28:33 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
Nov 08 10:28:33 ollama-ct bash[14137]:         return function(*args, **kwargs)
Nov 08 10:28:33 ollama-ct bash[14137]:                ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 08 10:28:33 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/callbacks.py", line 31, in on_after_component
Nov 08 10:28:33 ollama-ct bash[14137]:         settings.subscribe_update_button(*args, **kwargs)
Nov 08 10:28:33 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
Nov 08 10:28:33 ollama-ct bash[14137]:         return function(*args, **kwargs)
Nov 08 10:28:33 ollama-ct bash[14137]:                ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 08 10:28:33 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/settings.py", line 78, in subscribe_update_button
Nov 08 10:28:33 ollama-ct bash[14137]:         component.click(fn=update_comfyui)
Nov 08 10:28:33 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/lib/python3.11/site-packages/gradio/events.py", line 490, in event_trigger
Nov 08 10:28:33 ollama-ct bash[14137]:         raise AttributeError(
Nov 08 10:28:33 ollama-ct bash[14137]:     AttributeError: Cannot call click outside of a gradio.Blocks context.
Nov 08 10:28:33 ollama-ct bash[14137]: ---
Nov 08 10:28:33 ollama-ct bash[14137]: Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
Nov 08 10:28:33 ollama-ct bash[14137]: [GPU Setting] You will use 95.78% GPU memory (23228.00 MB) to load weights, and use 4.22% GPU memory (1024.00 MB) to do matrix computation.
Nov 08 10:28:34 ollama-ct bash[14137]: *** Error executing callback after_component_callback for /root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/callbacks.py
Nov 08 10:28:34 ollama-ct bash[14137]:     Traceback (most recent call last):
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/modules/script_callbacks.py", line 365, in after_component_callback
Nov 08 10:28:34 ollama-ct bash[14137]:         c.callback(component, **kwargs)
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
Nov 08 10:28:34 ollama-ct bash[14137]:         return function(*args, **kwargs)
Nov 08 10:28:34 ollama-ct bash[14137]:                ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/callbacks.py", line 30, in on_after_component
Nov 08 10:28:34 ollama-ct bash[14137]:         patches.watch_prompts(*args, **kwargs)
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
Nov 08 10:28:34 ollama-ct bash[14137]:         return function(*args, **kwargs)
Nov 08 10:28:34 ollama-ct bash[14137]:                ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/patches.py", line 34, in watch_prompts
Nov 08 10:28:34 ollama-ct bash[14137]:         getattr(component, event_listener)(
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/lib/python3.11/site-packages/gradio/events.py", line 490, in event_trigger
Nov 08 10:28:34 ollama-ct bash[14137]:         raise AttributeError(
Nov 08 10:28:34 ollama-ct bash[14137]:     AttributeError: Cannot call change outside of a gradio.Blocks context.
Nov 08 10:28:34 ollama-ct bash[14137]: ---
Nov 08 10:28:34 ollama-ct bash[14137]: *** Error executing callback after_component_callback for /root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/callbacks.py
Nov 08 10:28:34 ollama-ct bash[14137]:     Traceback (most recent call last):
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/modules/script_callbacks.py", line 365, in after_component_callback
Nov 08 10:28:34 ollama-ct bash[14137]:         c.callback(component, **kwargs)
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
Nov 08 10:28:34 ollama-ct bash[14137]:         return function(*args, **kwargs)
Nov 08 10:28:34 ollama-ct bash[14137]:                ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/callbacks.py", line 30, in on_after_component
Nov 08 10:28:34 ollama-ct bash[14137]:         patches.watch_prompts(*args, **kwargs)
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
Nov 08 10:28:34 ollama-ct bash[14137]:         return function(*args, **kwargs)
Nov 08 10:28:34 ollama-ct bash[14137]:                ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/extensions/sd-webui-comfyui/lib_comfyui/webui/patches.py", line 34, in watch_prompts
Nov 08 10:28:34 ollama-ct bash[14137]:         getattr(component, event_listener)(
Nov 08 10:28:34 ollama-ct bash[14137]:       File "/root/stable-diffusion-webui-forge/lib/python3.11/site-packages/gradio/events.py", line 490, in event_trigger
Nov 08 10:28:34 ollama-ct bash[14137]:         raise AttributeError(
Nov 08 10:28:34 ollama-ct bash[14137]:     AttributeError: Cannot call change outside of a gradio.Blocks context.
Nov 08 10:28:34 ollama-ct bash[14137]: ---
